name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Publish Self-Contained
      run: |
        dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true
        dir bin/Release/net8.0-windows/win-x64/publish/
        move "bin/Release/net8.0-windows/win-x64/publish/LeetCodeTimer.exe" "bin/Release/net8.0-windows/win-x64/publish/LeetCodeTimer-standalone.exe"
      
    - name: Publish Framework-Dependent
      run: |
        dotnet publish -c Release -r win-x64 --self-contained false /p:PublishSingleFile=true
        dir bin/Release/net8.0-windows/win-x64/publish/
        move "bin/Release/net8.0-windows/win-x64/publish/LeetCodeTimer.exe" "bin/Release/net8.0-windows/win-x64/publish/LeetCodeTimer-requires-dotnet.exe"
      
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          bin/Release/net8.0-windows/win-x64/publish/LeetCodeTimer-standalone.exe
          bin/Release/net8.0-windows/win-x64/publish/LeetCodeTimer-requires-dotnet.exe
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        generateReleaseNotes: true
        body: |
          ## LeetCode Timer Release
          
          Two versions are available:
          
          1. **LeetCodeTimer-standalone.exe**
             - Self-contained executable
             - Includes .NET runtime
             - Larger file size but works on any Windows machine
             - No additional dependencies required
          
          2. **LeetCodeTimer-requires-dotnet.exe**
             - Framework-dependent executable
             - Requires .NET 8.0 runtime
             - Smaller file size
             - Requires .NET 8.0 or later to be installed 